Repository entando-k8s/entando-k8s-app-plugin-link-controller, pull requests merged in 2020-04, with the labels that each got.

#3 Eng 366 delete link does not remove plugin path from app ingress
  .gitignore
  config/owasp-dependency-check-suppression.xml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/link/EntandoAppPluginLinkController.java
  src/test/java/org/entando/kubernetes/controller/link/inprocesstests/CreateAppPluginLinkTest.java
  src/test/java/org/entando/kubernetes/controller/link/interprocesstests/LinkEntandoPluginToAppIT.java
Labels: approved, size/M

#4 ENG-420 removes not necessary code and updates the tests
  src/main/java/org/entando/kubernetes/controller/link/DefaultEntandoComponentInstallerService.java
  src/main/java/org/entando/kubernetes/controller/link/EntandoAppPluginLinkController.java
  src/main/java/org/entando/kubernetes/controller/link/EntandoComponentInstallerService.java
  src/test/java/org/entando/kubernetes/controller/link/inprocesstests/CreateAppPluginLinkTest.java
  src/test/java/org/entando/kubernetes/controller/link/interprocesstests/LinkEntandoPluginToAppIT.java
Labels: approved, size/L

#6 ENG-420 removes the finalizers and cleanup stuff
  pom.xml
  src/main/java/org/entando/kubernetes/controller/link/EntandoAppPluginLinkController.java
  src/test/java/org/entando/kubernetes/controller/link/inprocesstests/CreateAppPluginLinkTest.java
  src/test/java/org/entando/kubernetes/controller/link/interprocesstests/LinkEntandoPluginToAppIT.java
Labels: approved, size/M

#7 Migrated to new pom and buildpack design
  charts/preview/requirements.yaml
  charts/preview/templates/default-rolebinding.yaml
  charts/preview/templates/operator-role.yaml
  charts/preview/templates/plugin-role.yaml
  charts/preview/templates/plugin-rolebinding.yaml
  charts/preview/templates/plugin-serviceaccount.yaml
  charts/preview/values.yaml
  jenkins-x.yml
  pom.xml
Labels: size/L
